[package]
name = "jrinx"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
no_test = []
colorful = []

[dependencies]
bitflags = "2.4.0"
buddy_system_allocator = { version = "0.9.0", features = ["const_fn"] }
cfg-if = "1.0.0"
fdt = "0.1.5"
getargs = { version = "0.5.0", default-features = false }
jrinx-addr-macro = { version = "0.1.0", path = "modules/addr-macro" }
jrinx-config = { version = "0.1.0", path = "modules/config" }
jrinx-devprober = { version = "0.1.0", path = "modules/devprober" }
jrinx-devprober-macro = { version = "0.1.0", path = "modules/devprober-macro" }
jrinx-error = { version = "0.1.0", path = "modules/error" }
jrinx-layout = { version = "0.1.0", path = "modules/layout" }
jrinx-serial-id = { version = "0.1.0", path = "modules/serial-id" }
jrinx-serial-id-macro = { version = "0.1.0", path = "modules/serial-id-macro" }
jrinx-testdef = { version = "0.1.0", path = "modules/testdef" }
jrinx-testdef-macro = { version = "0.1.0", path = "modules/testdef-macro" }
jrinx-util = { version = "0.1.0", path = "modules/util" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = { version = "0.4.20", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
spin = "0.9.8"

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.10.1"
sbi = "0.2.0"

[target.'cfg(target_arch = "riscv32")'.dependencies]
jrinx-addr = { version = "0.1.0", path = "modules/addr", features = ["pt_level_2"] }

[target.'cfg(target_arch = "riscv64")'.dependencies]
jrinx-addr = { version = "0.1.0", path = "modules/addr", features = ["pt_level_3"] }
